---
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - libgdal-dev
    - gdal-bin
python:
  install:
    - requirements: docs/rtd-requirements.txt
    - requirements: docs/requirements.txt
