---
name: Docker

on:
  workflow_dispatch:

  push:
    branches:
      - develop
    paths:
      - "**"

  release:
    types: [published]

env:
  IMAGE_NAME: opendatacube/explorer
  REGISTRY: ghcr.io

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event_name == 'release'

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      packages: write  # This is required for pushing to ghcr
      attestations: write # This is required for pushing the attestation

    steps:
      - name: Checkout git
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Get Git commit timestamps
        run: |
          TIMESTAMP=$(git log -1 --pretty=%ct pyproject.toml uv.lock cubedash)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Get and log unstable git tag
        if: github.event_name != 'release'
        run: |
          set -ex
          UNSTABLE_TAG=$(git describe --tags)
          echo "UNSTABLE_TAG=$UNSTABLE_TAG" >> $GITHUB_ENV

      - name: Build and Push unstable + latest Docker image tag
        if: github.event_name != 'release'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ENVIRONMENT=deployment
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.UNSTABLE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      # This section is for releases
      - name: Get and log tag for this build if it exists
        if: github.event_name == 'release'
        run: |
          set -ex
          RELEASE=$(git describe --abbrev=0 --tags)
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV

      - name: Build and Push release if we have a tag
        if: github.event_name == 'release'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: push
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ENVIRONMENT=deployment
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Attest Docker image
        if: github.event_name == 'release'
        uses: actions/attest-build-provenance@00014ed6ed5efc5b1ab7f7f34a39eb55d41aa4f8 # v3.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
