---
name: Docker

on:
  workflow_dispatch:

  push:
    branches:
      - develop

  release:
    types: [published]

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Compute version, tags and build epoch
        id: meta
        run: |
          set -euo pipefail
          VERSION="$(pipx run setuptools-scm)"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

  # Build (and push) a combined linux/amd64 + linux/arm64
  # See https://docs.docker.com/build/ci/github-actions/github-builder/build/
  # for documentation on this docker maintained workflow.
  build:
    needs: prepare
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1.17.0
    permissions:
      contents: read      # fetch the repository content
      id-token: write     # sign attestations and cache entries via OIDC
      packages: write     # push to GHCR
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      # cache: true
      # cache-mode: max
      sbom: true
      meta-images:  ghcr.io/${{ github.repository_owner }}/explorer
      meta-tags: |
        type=ref,event=tag
        type=ref,event=branch
        type=pep440,pattern={{version}}
        type=raw,value=${{ needs.prepare.outputs.version }}
      meta-annotations: |
        org.opencontainers.image.documentation=https://datacube-explorer.readthedocs.io/
        org.opencontainers.image.base.name=ghcr.io/osgeo/gdal
      meta-labels: |
        org.opencontainers.image.documentation=https://datacube-explorer.readthedocs.io/
        org.opencontainers.image.base.name=ghcr.io/osgeo/gdal
      set-meta-labels: true
      set-meta-annotations: true
      build-args: |
        ENVIRONMENT=deployment
        EXPLORER_VERSION=${{ needs.prepare.outputs.version }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  # Also do GitHub-native attestations for the pushed image
  attest:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # create an OIDC token to sign the attestation
      contents: read         # required by the action
      packages: write        # push the attestation alongside the image in GHCR
      attestations: write    # write the attestation to the GitHub store
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest image provenance
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          # Fully-qualified image name without no tag
          subject-name:  ghcr.io/${{ github.repository_owner }}/explorer
          subject-digest: ${{ needs.build.outputs.digest }}
          push-to-registry: true
