---
name: Linting

on:
  pull_request:
    paths:
      - '**'

  push:
    branches:
      - develop
    paths:
      - '**'

env:
  IMAGE_NAME: opendatacube/explorer

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker
        run: |
          make build
          docker-compose up -d

      - name: Run linting
        run: |
          make lint-docker
