---
name: Linting

on:
  pull_request:
    paths:
      - '**'

  push:
    branches:
      - develop
    paths:
      - '**'

env:
  IMAGE_NAME: opendatacube/explorer

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker
        run: |
          make build
          docker-compose up -d

      - name: Run linting
        run: |
          make lint-docker

      - name: Notify Slack for Failures
        uses: rtCamp/action-slack-notify@v2.0.0
        if: failure()
        env:
          SLACK_CHANNEL: explorer-alerts
          SLACK_COLOR: '#00a1de'
          SLACK_ICON: 'https://github.com/psf.png?size=48'
          SLACK_MESSAGE: ''
          SLACK_TITLE: Lint failure
          SLACK_USERNAME: Explorer linter
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
